#cloud-config
debug:
  verbose: true

timezone: Europe/Paris

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - zip
  - unzip
  - jq
  - nc

runcmd:
  # Install chrony
  - "yum -y erase ntp*"
  - "yum -y install chrony"
  - "service chronyd start"
  - "chkconfig chronyd on"
  - "chronyc sources -v"

write_files:
  - path: /etc/ecs/ecs.config
    content: |
      ECS_CLUSTER=cluster
      ECS_ENABLE_TASK_IAM_ROLE=false

final_message: "The ECS instance is finally up, after $UPTIME seconds"
